FROM python:3.8-alpine

RUN apk update && apk add curl
RUN apk add --update nodejs nodejs-npm

ENV WAITFORIT_VERSION="v2.4.1"
RUN curl -o /usr/local/bin/waitforit -sSL https://github.com/maxcnunes/waitforit/releases/download/$WAITFORIT_VERSION/waitforit-linux_amd64 \
    && chmod +x /usr/local/bin/waitforit

RUN npm install -g serverless
RUN npm install serverless-localstack
RUN npm install serverless-deployment-bucket --save-dev
RUN mkdir -p /usr/data-transform-serverless
WORKDIR /usr/data-transform-serverless

COPY requirements.txt .
COPY scripts ./scripts
COPY app ./app
COPY test ./test

# install dependencies
RUN pip install -r requirements.txt

RUN chmod +x scripts/standby-mode.sh
CMD waitforit -address=http://$LOCALSTACK_HOSTNAME:4566 -timeout=120 -- echo "INFO: RUNNING DOCKER" && . scripts/standby-mode.sh
