version: '3.8'

services:
  data-transform-serverless:
    privileged: true
    build: 
      context: ./
      dockerfile: Dockerfile.app
    ports:
      - "9000:8000"
    container_name: app
    network_mode: bridge
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT=http://${LOCALSTACK_REMOTE:-host.docker.internal}:4566
      - AWS_REGION=eu-central-1
      - AWS_ENV=test
      - LOCALSTACK_HOSTNAME=${LOCALSTACK_REMOTE:-host.docker.internal}

  localstack:
    privileged: true
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEFAULT_REGION=eu-central-1
      - SERVICES=serverless
      - DEBUG=${DEBUG- }
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data # Enables persistent storage e.g. on local disk
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
