
service: data-transform

plugins:
  - serverless-localstack

custom:
  localstack:
    host: http://${env:LOCALSTACK_HOSTNAME}
    stages:
      - local
  stages:
    - local
    - prod

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: python3.8
  region: eu-central-1
  stage: ${opt:stage, 'local'}
  deploymentPrefix: aws-lambda
  deploymentBucket: # when using localstack its important that before you deploy your lambda your s3 bucket already exists 
                    # you can do this automatically via added your aws cli create bucket commands to the create-bucket.sh script
    name: ${self:service}-${opt:stage}-deploy
    
package:
  individually: true
  exclude:
    - node_modules/**
    - venv/**
    - .pytest_cache/**
    - test/*

functions:
  processing:
    handler: file_processing.handler

